const { OpenAI } = require('openai');

let openai = null;

// Initialize OpenAI client if the key exists
if (process.env.OPENAI_API_KEY) {
  openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });
}

/**
 * Translates academic text.
 * Falls back to mock if API key is not present.
 */
exports.translateText = async (text, targetLanguage) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock translation.');
    await new Promise(resolve => setTimeout(resolve, 1500));
    return `[Mock Translation to ${targetLanguage}]: ${text}`;
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4",
      messages: [
        { role: "system", content: `You are an expert academic translator. Translate the following text into ${targetLanguage}, preserving formulas, citations, and formal tone.` },
        { role: "user", content: text }
      ],
      temperature: 0.3,
    });
    return response.choices[0].message.content;
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('Translation failed');
  }
};

/**
 * Generates an embeddings vector for text chunks.
 */
exports.generateEmbedding = async (text) => {
  if (!openai) return Array(1536).fill(0.01); // Mock vector

  const response = await openai.embeddings.create({
    model: "text-embedding-ada-002",
    input: text,
  });
  return response.data[0].embedding;
};

/**
 * RAG Chat response given a context.
 */
exports.ragChat = async (prompt, contextDocs) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock RAG response.');
    await new Promise(resolve => setTimeout(resolve, 1500));
    return `[Mock Copilot Response based on ${contextDocs.length} documents]: I found some interesting insights regarding your query: "${prompt}".`;
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4",
      messages: [
        { role: "system", content: "You are a Research Copilot. Answer the user's prompt using ONLY the provided context. If the context does not contain the answer, say you don't know." },
        { role: "user", content: `Context:\n${contextDocs.join('\n\n')}\n\nPrompt: ${prompt}` }
      ],
      temperature: 0.2,
    });
    return response.choices[0].message.content;
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('RAG Chat failed');
  }
};

/**
 * Generates a structured PPT JSON based on a prompt.
 */
exports.generatePPT = async (topic, structure, style, tone) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock PPT generation.');
    await new Promise(resolve => setTimeout(resolve, 2000));
    return [
      { title: topic || "AI Generated Presentation", subtitle: "A Paradigm Shift", content: `Style: ${style} | Tone: ${tone}` },
      { title: "Introduction", content: "• This slide was generated by ScholarMind AI.\n• It provides automated insights.\n• You can download this as a real PPTX." },
      { title: "Methodology", content: "• Research was conducted using advanced neural networks.\n• Data was synthesized from multiple sources." },
      { title: "Conclusion", content: "• AI greatly accelerates academic workflows.\n• Thank you for watching." }
    ];
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4-turbo-preview",
      messages: [
        { role: "system", content: `You are an expert academic presentation creator. Generate a JSON array of slide objects. Each object must have 'title', 'subtitle' (optional), and 'content' (bullet points separated by newlines). Use a strictly ${style} and formal ${tone} style suitable for a ${structure} context.` },
        { role: "user", content: `Create a professional academic presentation about: ${topic}` }
      ],
      response_format: { type: "json_object" },
      temperature: 0.7,
    });
    const result = JSON.parse(response.choices[0].message.content);
    return result.slides || result;
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('PPT generation failed');
  }
};

/**
 * Generates a video script and scene description.
 */
exports.generateVideoScript = async (prompt, style, audio) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock Video generation.');
    await new Promise(resolve => setTimeout(resolve, 2500));
    return {
      title: `Generated Video: ${prompt}`,
      scenes: [
        { scene: 1, visual: "Fade in to a modern laboratory setup.", narration: "Welcome to our exploration of advanced concepts." },
        { scene: 2, visual: "Animated graphs showing exponential growth.", narration: "As you can see, the data indicates a clear upward trend." },
        { scene: 3, visual: "Conclusion slide with logo.", narration: "Thank you for tuning in to ScholarMind." }
      ]
    };
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4-turbo-preview",
      messages: [
        { role: "system", content: `You are an expert academic video director. Generate a JSON object containing a 'title' and a 'scenes' array. Each scene should have 'scene' (number), 'visual' (description of what is shown), and 'narration' (what the ${audio} voiceover says). Style: ${style}.` },
        { role: "user", content: `Create a video script about: ${prompt}` }
      ],
      response_format: { type: "json_object" },
      temperature: 0.7,
    });
    return JSON.parse(response.choices[0].message.content);
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('Video generation failed');
  }
};

/**
 * Analyzes data and returns insights.
 */
exports.analyzeData = async (dataContext) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock Data Analysis.');
    await new Promise(resolve => setTimeout(resolve, 1800));
    return {
      stats: { mean: 42.5, sd: 12.8, pVal: 0.042, correlation: 0.85, missingValues: 2 },
      interpretation: "The analysis reveals a statistically significant correlation (r = 0.85, p = 0.042) between the studied variables. The observed mean (42.5) indicates a substantial deviation from the control group, suggesting high impact publication readiness for this dataset."
    };
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4-turbo-preview",
      messages: [
        { role: "system", content: "You are a senior data scientist. Analyze the provided dataset summary. Return a JSON object with 'stats' (mean, sd, pVal, correlation, missingValues) and 'interpretation' (a paragraph explaining the results)." },
        { role: "user", content: `Analyze this data: ${dataContext}` }
      ],
      response_format: { type: "json_object" },
      temperature: 0.3,
    });
    return JSON.parse(response.choices[0].message.content);
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('Data analysis failed');
  }
};

/**
 * Generates a thesis chapter.
 */
exports.generateThesisChapter = async (chapterTitle, projectContext) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock Thesis generation.');
    await new Promise(resolve => setTimeout(resolve, 2000));
    return `[AI Generated Chapter: ${chapterTitle}]\n\nBased on the provided context (${projectContext}), this chapter explores the fundamental aspects of the research. The primary focus is to establish a clear methodological framework that supports the overarching hypothesis.\n\nFurthermore, the literature reviewed suggests a significant gap in the current understanding, which this thesis aims to address through rigorous empirical analysis.`;
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4",
      messages: [
        { role: "system", content: "You are an expert academic ghostwriter. Draft a highly professional, academic chapter for a thesis." },
        { role: "user", content: `Draft the chapter titled "${chapterTitle}". Use this project context: ${projectContext}` }
      ],
      temperature: 0.7,
    });
    return response.choices[0].message.content;
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('Thesis generation failed');
  }
};

/**
 * Generates visualization structure (e.g. mind map nodes).
 */
exports.generateVisualizationData = async (prompt, type) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock Visualization generation.');
    await new Promise(resolve => setTimeout(resolve, 2000));
    return {
      nodes: [
        { id: "1", label: "Core Concept: " + (prompt || "AI") },
        { id: "2", label: "Related Idea A" },
        { id: "3", label: "Related Idea B" },
        { id: "4", label: "Sub-idea A1" }
      ],
      edges: [
        { source: "1", target: "2" },
        { source: "1", target: "3" },
        { source: "2", target: "4" }
      ]
    };
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4-turbo-preview",
      messages: [
        { role: "system", content: `You are an expert data visualization architect. Generate a JSON object representing a ${type} graph with a 'nodes' array (each with 'id' and 'label') and an 'edges' array (each with 'source' and 'target' IDs).` },
        { role: "user", content: `Create a visualization structure for: ${prompt}` }
      ],
      response_format: { type: "json_object" },
      temperature: 0.5,
    });
    return JSON.parse(response.choices[0].message.content);
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('Visualization generation failed');
  }
};

/**
 * Humanizes AI-generated text.
 */
exports.humanizeText = async (text) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock Humanize.');
    await new Promise(resolve => setTimeout(resolve, 1500));
    return text + "\n\n[Humanized by ScholarMind AI: Text adjusted for natural flow and variance.]";
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4-turbo-preview",
      messages: [
        { role: "system", content: "You are an expert academic editor. Rewrite the following text to make it sound more human, natural, and bypass AI detectors while maintaining formal academic tone." },
        { role: "user", content: text }
      ],
      temperature: 0.8,
    });
    return response.choices[0].message.content;
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('Humanize failed');
  }
};

/**
 * Generates a voice narration for text.
 */
exports.generateVoice = async (text) => {
  // In a real app, this would use OpenAI TTS API
  await new Promise(resolve => setTimeout(resolve, 1500));
  return {
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    status: 'success'
  };
};

/**
 * Searches for academic papers based on query.
 */
exports.searchPapers = async (query) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock Paper Search.');
    await new Promise(resolve => setTimeout(resolve, 2000));
    return [
      { 
        title: `Advanced Meta-Analysis of ${query}`, 
        author: "Dr. A. Scholar et al.", 
        journal: "Nature Communications", 
        year: 2024, 
        citations: 124,
        abstract: "This study explores the foundational and emerging concepts in the field, providing a comprehensive overview."
      },
      { 
        title: `Empirical Evidence in ${query} Research`, 
        author: "Prof. J. Doe", 
        journal: "Journal of Biochemistry", 
        year: 2023, 
        citations: 89,
        abstract: "A deep dive into the experimental methodologies and results that have shaped our understanding."
      }
    ];
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4-turbo-preview",
      messages: [
        { role: "system", content: "You are an expert academic librarian. Search and return a JSON object with a 'results' array of 5 realistic (not necessarily real) academic papers. Each must have: title, author, journal, year (number), citations (number), abstract." },
        { role: "user", content: `Search for papers about: ${query}` }
      ],
      response_format: { type: "json_object" },
    });
    return JSON.parse(response.choices[0].message.content).results;
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('Search failed');
  }
};

/**
 * Audits research for gaps, contradictions, and novelty.
 */
exports.auditResearch = async (topic) => {
  if (!openai) {
    console.warn('[OpenAI Service] No API Key found. Using mock Audit.');
    await new Promise(resolve => setTimeout(resolve, 2500));
    return {
      noveltyScore: 92,
      contradictions: 2,
      gapsFound: 4,
      citationsNeeded: 12,
      validity: 'High',
      findings: [
        { type: 'contradiction', text: 'Inconsistent with Nature 2024 (Conflict ID: 42)' },
        { type: 'gap', text: 'Unexplored Demographic: Southeast Asia' }
      ]
    };
  }

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4-turbo-preview",
      messages: [
        { role: "system", content: "You are a senior academic auditor. Return a JSON object with: noveltyScore (number), contradictions (number), gapsFound (number), citationsNeeded (number), validity (string), and a 'findings' array of objects with {type: 'contradiction'|'gap', text}." },
        { role: "user", content: `Audit this research context: ${topic}` }
      ],
      response_format: { type: "json_object" },
    });
    return JSON.parse(response.choices[0].message.content);
  } catch (error) {
    console.error('[OpenAI Service Error]', error);
    throw new Error('Audit failed');
  }
};
